import argparse
import json
import os
import urllib.error
import urllib.request
from typing import Any, Dict


CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
ML_ROOT = os.path.abspath(os.path.join(CURRENT_DIR, ".."))


def load_metadata(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def post_json(url: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    data = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError("HTTP %s from %s: %s" % (exc.code, url, body))


def build_registry_payload(metadata: Dict[str, Any], status: str) -> Dict[str, Any]:
    return {
        "modelVersion": metadata["modelVersion"],
        "modelType": metadata.get("modelType", "UNKNOWN"),
        "modelUri": metadata.get("modelUri", "best_risk_model.pkl"),
        "thresholdUri": metadata.get("thresholdUri", "threshold.json"),
        "featureColumnsUri": metadata.get("featureColumnsUri", "feature_columns.json"),
        "metadataUri": metadata.get("metadataUri", "model_metadata.json"),
        "status": status,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Register the latest Zephyr-Watch model artifact through the API.")
    parser.add_argument(
        "--metadata",
        default=os.path.join(ML_ROOT, "models", "model_metadata.json"),
        help="Path to model_metadata.json generated by train_baselines.py.",
    )
    parser.add_argument("--api-base", default="http://localhost:8080", help="Zephyr API base URL.")
    parser.add_argument("--status", default="READY", help="Initial registry status.")
    parser.add_argument("--activate", action="store_true", help="Mark this model as ACTIVE after registration.")
    args = parser.parse_args()

    metadata = load_metadata(args.metadata)
    payload = build_registry_payload(metadata, args.status)
    register_url = args.api_base.rstrip("/") + "/api/models"
    register_response = post_json(register_url, payload)
    print(json.dumps(register_response, ensure_ascii=False, indent=2))

    if args.activate:
        model_version = payload["modelVersion"]
        activate_url = args.api_base.rstrip("/") + "/api/models/%s/activate" % model_version
        activate_response = post_json(activate_url, {})
        print(json.dumps(activate_response, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
